import { IPrevision } from "../../utils/types/prevision.interface";
import { convertENDateToFr } from "../../utils/scripts/utils.ts";

export interface IServerPrevision {
  cle: string;
  societe: string;
  code_journal: string;
  date_piece: string;
  date_saisie: string;
  auteur_saisie: string;
  no_compte_general: string;
  libelle_compte_general: string;
  no_compte_tiers: string;
  libelle_compte_tiers: string;
  cle_rubrique_treso: string;
  rubrique_treso: string;
  libelle_ecriture_prefixe: string;
  libelle_ecriture_mois: string;
  libelle_ecriture_annee: string;
  libelle_ecriture_trimestre: string;
  libelle_ecriture_beneficiaire: string;
  libelle_ecriture: string;
  date_echeance: string;
  no_semaine_echeance: string;
  date_ordo: string;
  no_semaine_ordo: string;
  debit: string;
  credit: string;
  code_operation: string;
  cle_ecriture: string;
  compte_regroupement: string;
  no_compte_banque: string;
  date_paiement: string;
  mode_reglement: string;
  statut: string;
  dh_statut: string;
  auteur_statut: string;
  manu: string;
  commentaire: string;
  date_solde: string;
  ref_source_tiers: string;
  cle_courrier: string;
  reference_paiement: string;
  cle_facture: string;
  cle_budget: string;
  cle_commande: string;
  code_tiers_payeur: string;
  inter: string;
  cle_accord_partenaire: string;
  marque: string;
  mat_mark: string;
  avec_tva: string;
  taux_tva1: string;
  montant_tva1: string;
  taux_tva2: string;
  montant_tva2: string;
  taux_tva3: string;
  montant_tva3: string;
  taux_tva4: string;
  montant_tva4: string;
  taux_tva5: string;
  montant_tva5: string;
  cle_prelevement: string;
  cle_etale: string;
}

export const previsionModel = (
  serverPrevision: IServerPrevision,
): IPrevision => {
  return {
    cle: serverPrevision.cle,
    societe: serverPrevision.societe,
    codeJournal: serverPrevision.code_journal,
    datePiece: convertENDateToFr(serverPrevision.date_piece),
    dateSaisie: serverPrevision.date_saisie,
    auteurSaisie: serverPrevision.auteur_saisie,
    noCompteGeneral: serverPrevision.no_compte_general,
    libelleCompteGeneral: serverPrevision.libelle_compte_general,
    noCompteTiers: serverPrevision.no_compte_tiers,
    libelleCompteTiers: serverPrevision.libelle_compte_tiers,
    cleRubriqueTreso: serverPrevision.cle_rubrique_treso,
    rubriqueTreso: serverPrevision.rubrique_treso,
    libelleEcriturePrefixe: serverPrevision.libelle_ecriture_prefixe,
    libelleEcritureMois: serverPrevision.libelle_ecriture_mois,
    libelleEcritureAnnee: serverPrevision.libelle_ecriture_annee,
    libelleEcritureTrimestre: serverPrevision.libelle_ecriture_trimestre,
    libelleEcritureBeneficiaire: serverPrevision.libelle_ecriture_beneficiaire,
    libelleEcriture: serverPrevision.libelle_ecriture,
    dateEcheance: convertENDateToFr(serverPrevision.date_echeance),
    noSemaineEcheance: serverPrevision.no_semaine_echeance,
    dateOrdo: serverPrevision.date_ordo,
    noSemaineOrdo: serverPrevision.no_semaine_ordo,
    debit: serverPrevision.debit,
    credit: serverPrevision.credit,
    codeOperation: serverPrevision.code_operation,
    cleEcriture: serverPrevision.cle_ecriture,
    compteRegroupement: serverPrevision.compte_regroupement,
    noCompteBanque: serverPrevision.no_compte_banque,
    datePaiement: serverPrevision.date_paiement,
    modeReglement: serverPrevision.mode_reglement,
    statut: serverPrevision.statut,
    dhStatut: serverPrevision.dh_statut,
    auteurStatut: serverPrevision.auteur_statut,
    manu: serverPrevision.manu,
    commentaire: serverPrevision.commentaire,
    dateSolde: serverPrevision.date_solde,
    refSourceTiers: serverPrevision.ref_source_tiers,
    cleCourrier: serverPrevision.cle_courrier,
    referencePaiement: serverPrevision.reference_paiement,
    cleFacture: serverPrevision.cle_facture,
    cleBudget: serverPrevision.cle_budget,
    cleCommande: serverPrevision.cle_commande,
    codeTiersPayeur: serverPrevision.code_tiers_payeur,
    inter: serverPrevision.inter,
    cleAccordPartenaire: serverPrevision.cle_accord_partenaire,
    marque: serverPrevision.marque,
    matMark: serverPrevision.mat_mark,
    avecTva: serverPrevision.avec_tva,
    tauxTva1: serverPrevision.taux_tva1,
    montantTva1: serverPrevision.montant_tva1,
    tauxTva2: serverPrevision.taux_tva2,
    montantTva2: serverPrevision.montant_tva2,
    tauxTva3: serverPrevision.taux_tva3,
    montantTva3: serverPrevision.montant_tva3,
    tauxTva4: serverPrevision.taux_tva4,
    montantTva4: serverPrevision.montant_tva4,
    tauxTva5: serverPrevision.taux_tva5,
    montantTva5: serverPrevision.montant_tva5,
    clePrelevement: serverPrevision.cle_prelevement,
    cleEtale: serverPrevision.cle_etale,
  };
};
